language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

before_install:
  - export COMPONENTS=build-tools-20.0.0,android-16
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env
