language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

before_install:
  - mkdir -p ~/.m2/repository
  - cp -R $ANDROID_HOME/extras/android/m2repository/com ~/.m2/repository
  - git clone https://github.com/simpligility/maven-android-sdk-deployer.git ~/maven-android-sdk-deployer
  - pushd ~/maven-android-sdk-deployer; mvn install -P 5.1; mvn install -P extra; popd

install: "mvn clean"
script: "mvn -Dmaven.javadoc.skip=true install -B"

sudo: false

cache:
  directories:
    - $HOME/.m2
